### ISSUE TITLE
如何设置 favicon.ico 网站图标？

### ISSUE THREAD

**Issue by yodhcn** [iplaycode/webstack-hugo#6]
我尝试将 ```favicon.ico``` 上传到 ```/static``` 文件夹，build 后也成功打包进 ```/public``` 文件夹下，但部署后仍然没有正常显示网站图标。
请问我该如何设置网站图标？

**Comment by iplaycode** [comment]
> 我尝试将 `favicon.ico` 上传到 `/static` 文件夹，build 后也成功打包进 `/public` 文件夹下，但部署后仍然没有正常显示网站图标。 请问我该如何设置网站图标？

./assets/favicon.png
